[loggers]
keys=root,InitializeScripts,IntegrationTime,LensAlignment,ProcessSpecific,FileIO,InitializeGeneralUtils,PeakFitting,InitializePlottingUtils,StandardPlots

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=defaultFormatter

[logger_root]
level=INFO
handlers=consoleHandler,fileHandler

[logger_InitializeScripts]
level=INFO
handlers=
qualname=InitializeScripts
propagate=1

[logger_IntegrationTime]
level=INFO
handlers=
qualname=IntegrationTime
propagate=1

[logger_LensAlignment]
level=INFO
handlers=
qualname=LensAlignment
propagate=1

[logger_ProcessSpecific]
level=INFO
handlers=
qualname=ProcessSpecific
propagate=1

[logger_FileIO]
level=INFO
handlers=
qualname=FileIO
propagate=1

[logger_InitializeGeneralUtils]
level=INFO
handlers=
qualname=InitializeGeneralUtils
propagate=1

[logger_PeakFitting]
level=INFO
handlers=
qualname=PeakFitting
propagate=1

[logger_InitializePlottingUtils]
level=INFO
handlers=
qualname=InitializePlottingUtils
propagate=1

[logger_StandardPlots]
level=INFO
handlers=
qualname=StandardPlots
propagate=1

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=defaultFormatter
args=(sys.stderr,)

[handler_fileHandler]
class=handlers.TimedRotatingFileHandler
level=INFO
formatter=defaultFormatter
args=('%(logdir)s/application_%(logdate)s.log', 'midnight', 1, 30, 'utf-8')

[formatter_defaultFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
